//! Optional operation-level oracle, generated by tools/dump_ar_debug.py.
use super::*;

#[test]
#[ignore = "requires YUE2_FIXTURES, CUDA, and tools/dump_ar_debug.py"]
fn ar_operations_oracle() -> Result<()> {
    let Some(root) = std::env::var_os("YUE2_FIXTURES") else {
        eprintln!("SKIP: YUE2_FIXTURES is unset");
        return Ok(());
    };
    ensure!(
        std::env::var("CUDA_VISIBLE_DEVICES").as_deref() == Ok("0"),
        "Use only GPU 0"
    );
    let mut root = PathBuf::from(root);
    if !root.join("manifest.json").is_file() {
        root = root.join("first-song");
    }
    let manifest: serde_json::Value =
        serde_json::from_slice(&std::fs::read(root.join("manifest.json"))?)?;
    let path = PathBuf::from(manifest["weights"]["model"]["path"].as_str().unwrap());
    let device = Device::new_cuda(0)?;
    // SAFETY: reference files are immutable during the test.
    let model =
        unsafe { YuE2ForCausalLM::from_pretrained(path.parent().unwrap(), DType::BF16, &device)? };
    let tensors =
        candle_core::safetensors::load(root.join("debug/ar_operations.safetensors"), &Device::Cpu)?;
    let get = |name: &str| -> Result<Tensor> {
        Ok(tensors[name].to_device(&device)?.to_dtype(DType::BF16)?)
    };
    let compare = |name: &str, actual: Tensor| -> Result<()> {
        let actual = actual
            .to_dtype(DType::F32)?
            .flatten_all()?
            .to_vec1::<f32>()?;
        let expected = tensors[name].flatten_all()?.to_vec1::<f32>()?;
        ensure!(actual.len() == expected.len(), "Wrong shape: {name}");
        let exact = actual.iter().zip(&expected).filter(|(a, b)| a == b).count();
        let diff = actual
            .iter()
            .zip(&expected)
            .map(|(a, b)| (a - b).abs())
            .fold(0f32, f32::max);
        println!("{name}: exact {exact}/{}; max_abs={diff}", actual.len());
        Ok(())
    };
    let layer = &model.model.layers[0];
    compare(
        "input_layernorm.output",
        layer
            .input_layernorm
            .forward(&get("input_layernorm.input")?)?,
    )?;
    let attn = &layer.self_attn;
    for (name, linear) in [
        ("q_proj", &attn.q_proj),
        ("k_proj", &attn.k_proj),
        ("v_proj", &attn.v_proj),
        ("o_proj", &attn.o_proj),
    ] {
        compare(
            &format!("self_attn.{name}.output"),
            linear_forward(linear, &get(&format!("self_attn.{name}.input"))?)?,
        )?;
    }
    compare(
        "self_attn.q_norm.output",
        attn.q_norm.forward(&get("self_attn.q_norm.input")?)?,
    )?;
    compare(
        "self_attn.k_norm.output",
        attn.k_norm.forward(&get("self_attn.k_norm.input")?)?,
    )?;
    let positions = Tensor::arange(0u32, 64, &device)?.unsqueeze(0)?;
    let (cos, sin) = model.model.rotary_emb.forward(&positions)?;
    compare("cos", cos.clone())?;
    compare("sin", sin.clone())?;
    compare(
        "q_rot",
        model
            .model
            .rotary_emb
            .apply(&get("self_attn.q_norm.output")?, &cos, &sin)?,
    )?;
    compare(
        "k_rot",
        model
            .model
            .rotary_emb
            .apply(&get("self_attn.k_norm.output")?, &cos, &sin)?,
    )?;
    let out = attn.sdpa(
        &get("q_rot")?.transpose(1, 2)?,
        &get("k_rot")?.transpose(1, 2)?,
        &get("v")?.transpose(1, 2)?,
        0,
    )?;
    compare(
        "self_attn.o_proj.input",
        out.transpose(1, 2)?.contiguous()?.reshape((1, 64, 2048))?,
    )?;
    compare(
        "post_attention_layernorm.output",
        layer
            .post_attention_layernorm
            .forward(&get("post_attention_layernorm.input")?)?,
    )?;
    let mlp = &layer.mlp;
    for (name, linear) in [
        ("gate_proj", &mlp.gate_proj),
        ("up_proj", &mlp.up_proj),
        ("down_proj", &mlp.down_proj),
    ] {
        compare(
            &format!("mlp.{name}.output"),
            linear_forward(linear, &get(&format!("mlp.{name}.input"))?)?,
        )?;
    }
    let gate = get("mlp.gate_proj.output")?
        .to_dtype(DType::F32)?
        .silu()?
        .to_dtype(DType::BF16)?;
    compare("mlp.down_proj.input", (&gate * get("mlp.up_proj.output")?)?)?;
    Ok(())
}
